### PR TITLE
98 Create separate files for `scda.2021` datasets

### PR DESCRIPTION
**Pull request by edelarua**
Part of https://github.com/insightsengineering/scda/issues/98

### CODE REVIEW

**Comment by pawelru** [comment]
@shajoezhu do we still care about 2021? I would assume that we will be slowly archiving this

**Comment by Melkiades** [comment]
> @shajoezhu do we still care about 2021? I would assume that we will be slowly archiving this

I agree and I am unsure if any code is using `scda.2021` atm. @shajoezhu shall we start the deprecation?

**Comment by pawelru** [comment]
> > @shajoezhu do we still care about 2021? I would assume that we will be slowly archiving this
> 
> I agree and I am unsure if any code is using `scda.2021` atm. @shajoezhu shall we start the deprecation?

To my surprise there are quite a few pkgs that uses `scda.2021` and not `scda.2022` -> https://github.com/search?q=org%3Ainsightsengineering+scda.2021+filename%3ADESCRIPTION&type=Code&ref=advsearch&l=&l=
Let me bring this to core-dev team

**Review by shajoezhu — APPROVED** [review]
lgtm! thanks @edelarua

**Pull request merged**
